# i18n and l10n makefile for lexitron documentation
# jcj 2020-02-11, 2020-05-12, 2020-06-16

DOMAIN=lexitron-documentation
LOCALES=/home/jason/locales
TEMPLATE=$(LOCALES)/$(DOMAIN).pot
PYTHON_VERSION=python3.6
LOCAL_LIB=/home/jason/.local/lib/$(PYTHON_VERSION)/site-packages
LOCAL_IMPORTS=$(LOCAL_LIB)/error.py $(LOCAL_LIB)/textutils.py
SOURCES=lexDoc.py $(LOCAL_IMPORTS)

help:
	@echo 'Type: make xgettext|msginit|msgmerge|msgfmt'

xgettext:
	xgettext --from-code=utf-8 --keyword=__:1c,2 \
		 -o $(TEMPLATE) $(SOURCES)

msginit:
	msginit -l en -i $(TEMPLATE) -o $(LOCALES)/en/LC_MESSAGES/$(DOMAIN).po
	msginit -l fr -i $(TEMPLATE) -o $(LOCALES)/fr/LC_MESSAGES/$(DOMAIN).po

msgmerge:
	msgmerge --update \
		$(LOCALES)/en/LC_MESSAGES/$(DOMAIN).po $(TEMPLATE)
	msgmerge --update \
		$(LOCALES)/fr/LC_MESSAGES/$(DOMAIN).po $(TEMPLATE)

msgfmt:
	msgfmt -o $(LOCALES)/en/LC_MESSAGES/$(DOMAIN).mo \
		$(LOCALES)/en/LC_MESSAGES/$(DOMAIN).po
	msgfmt -o $(LOCALES)/fr/LC_MESSAGES/$(DOMAIN).mo \
		$(LOCALES)/fr/LC_MESSAGES/$(DOMAIN).po
